"""Agregar campo estado para eliminación lógica

Revision ID: 0efe1c1c239e
Revises: 
Create Date: 2025-03-10 19:47:49.775991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0efe1c1c239e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.Integer(), nullable=True))

    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.Integer(), nullable=True))

    with op.batch_alter_table('detalle_venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.Integer(), nullable=True))

    with op.batch_alter_table('empleado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.Integer(), nullable=True))

    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.Integer(), nullable=True))

    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.Integer(), nullable=True))

    with op.batch_alter_table('subcategoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.Integer(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.Integer(), nullable=True))

    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado_registro', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.drop_column('estado_registro')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('estado')

    with op.batch_alter_table('subcategoria', schema=None) as batch_op:
        batch_op.drop_column('estado')

    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.drop_column('estado')

    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.drop_column('estado')

    with op.batch_alter_table('empleado', schema=None) as batch_op:
        batch_op.drop_column('estado')

    with op.batch_alter_table('detalle_venta', schema=None) as batch_op:
        batch_op.drop_column('estado')

    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('estado')

    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.drop_column('estado')

    # ### end Alembic commands ###
