"""Add invoice fields to Venta model

Revision ID: 2f52fb04163f
Revises: 0efe1c1c239e
Create Date: 2025-03-12 19:58:16.799396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f52fb04163f'
down_revision = '0efe1c1c239e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtotal', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('iva', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('descuento', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('descuento_porcentaje', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('numero_factura', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('metodo_pago', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('notas', sa.Text(), nullable=True))
        batch_op.create_unique_constraint(None, ['numero_factura'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('notas')
        batch_op.drop_column('metodo_pago')
        batch_op.drop_column('numero_factura')
        batch_op.drop_column('descuento_porcentaje')
        batch_op.drop_column('descuento')
        batch_op.drop_column('iva')
        batch_op.drop_column('subtotal')

    # ### end Alembic commands ###
