"""Agregar campo rol a modelo User

Revision ID: 902d26586618
Revises: 2f52fb04163f
Create Date: 2025-03-12 20:46:17.954024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '902d26586618'
down_revision = '2f52fb04163f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rol', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('rol')

    # ### end Alembic commands ###
